// 影视游戏配置 - TS 形式
// 编辑器保存时会直接更新此文件

export interface MoviesGamesItem {
	id: string;
	title: string;
	name_cn: string;
	category: string;
	status: number;
	score: number;
	image: string;
	tags: string[];
	comment: string;
	updated_at: string;
}

// 影视游戏页面配置
export const moviesGamesPageConfig = {
	enable: true,
	editable: true,
};

// 影视游戏数据配置
export const moviesGamesConfig: MoviesGamesItem[] = [
	{
		id: "/bangumi/game/王者荣耀/",
		title: "王者荣耀3333",
		name_cn: "王者荣耀",
		category: "game",
		status: 3,
		score: 0,
		image: "https://ph.0824.uk/file/game/王者荣耀.jpg",
		tags: ["游戏"],
		comment: "",
		updated_at: "2026-07-01T21:21:25.779Z",
	},
	{
		id: "/bangumi/anime/极速风流/",
		title: "极速风流",
		name_cn: "极速风流",
		category: "anime",
		status: 2,
		score: 9,
		image: "https://ph.0824.uk/file/anime/极速风流.jpg",
		tags: ["剧情","动作"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.806Z",
	},
	{
		id: "/bangumi/anime/茶馆/",
		title: "茶馆",
		name_cn: "茶馆",
		category: "anime",
		status: 2,
		score: 10,
		image: "https://ph.0824.uk/file/anime/茶馆.jpg",
		tags: ["剧情"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.806Z",
	},
	{
		id: "/bangumi/anime/侏罗纪世界/",
		title: "侏罗纪世界",
		name_cn: "侏罗纪世界",
		category: "anime",
		status: 2,
		score: 8,
		image: "https://ph.0824.uk/file/anime/侏罗纪世界.jpg",
		tags: ["冒险","科幻"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.806Z",
	},
	{
		id: "/bangumi/anime/凡人修仙传/",
		title: "凡人修仙传",
		name_cn: "凡人修仙传",
		category: "anime",
		status: 3,
		score: 10,
		image: "https://ph.0824.uk/file/anime/凡人修仙传.jpg",
		tags: ["动画"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.806Z",
	},
	{
		id: "/bangumi/anime/给阿嬷的情书/",
		title: "给阿嬷的情书",
		name_cn: "给阿嬷的情书",
		category: "anime",
		status: 2,
		score: 10,
		image: "https://ph.0824.uk/file/anime/给阿嬷的情书.jpg",
		tags: ["剧情，感情"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.806Z",
	},
	{
		id: "/bangumi/anime/食神/",
		title: "食神",
		name_cn: "食神",
		category: "movie",
		status: 2,
		score: 9,
		image: "https://ph.0824.uk/file/anime/食神.jpg",
		tags: ["周星驰"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/唐人街探案/",
		title: "唐人街探案",
		name_cn: "唐人街探案",
		category: "movie",
		status: 2,
		score: 0,
		image: "https://ph.0824.uk/file/anime/唐人街探案.jpg",
		tags: [],
		comment: "",
		updated_at: "2026-07-01T22:13:34.070Z",
	},
	{
		id: "/bangumi/anime/河狸变身计划/",
		title: "河狸变身计划",
		name_cn: "河狸变身计划",
		category: "anime",
		status: 2,
		score: 0,
		image: "https://ph.0824.uk/file/anime/河狸变身计划.jpg",
		tags: [],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/爱乐之城/",
		title: "爱乐之城",
		name_cn: "爱乐之城",
		category: "anime",
		status: 2,
		score: 0,
		image: "https://ph.0824.uk/file/anime/爱乐之城.jpg",
		tags: ["喜剧","剧情","爱情"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/黑暗荣耀第二季/",
		title: "黑暗荣耀第二季",
		name_cn: "黑暗荣耀第二季",
		category: "anime",
		status: 2,
		score: 9,
		image: "https://re.tsh520.cn/blogre/黑暗荣耀2.webp",
		tags: ["校园","电视剧"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/黑暗荣耀1/",
		title: "黑暗荣耀1",
		name_cn: "黑暗荣耀1",
		category: "anime",
		status: 2,
		score: 10,
		image: "https://re.tsh520.cn/blogre/黑暗荣耀1.webp",
		tags: ["校园","电视剧"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/消失的人/",
		title: "消失的人",
		name_cn: "消失的人",
		category: "anime",
		status: 2,
		score: 8.5,
		image: "https://re.tsh520.cn/blogre/消失的人.webp",
		tags: ["悬疑"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/鬼客/",
		title: "鬼客",
		name_cn: "鬼客",
		category: "anime",
		status: 2,
		score: 9,
		image: "https://re.tsh520.cn/blogre/鬼客.webp",
		tags: ["鬼片","纪录片"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/夺命许愿/",
		title: "夺命许愿",
		name_cn: "夺命许愿",
		category: "anime",
		status: 2,
		score: 8.5,
		image: "https://re.tsh520.cn/blogre/夺命许愿.webp",
		tags: ["鬼片","电视剧"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/蜘蛛侠/",
		title: "蜘蛛侠",
		name_cn: "蜘蛛侠",
		category: "anime",
		status: 2,
		score: 9,
		image: "https://re.tsh520.cn/Acover/蜘蛛侠1.webp",
		tags: ["科幻","神作"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/爆裂鼓手/",
		title: "爆裂鼓手",
		name_cn: "爆裂鼓手",
		category: "anime",
		status: 2,
		score: 9,
		image: "https://ph.0824.uk/file/anime/爆裂鼓手.jpg",
		tags: ["电影"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/迷雾/",
		title: "迷雾",
		name_cn: "迷雾",
		category: "anime",
		status: 2,
		score: 8.1,
		image: "https://re.tsh520.cn/Acover/p2363134750.webp",
		tags: ["电影"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/game/英雄联盟/",
		title: "英雄联盟",
		name_cn: "英雄联盟",
		category: "game",
		status: 5,
		score: 9.5,
		image: "https://re.tsh520.cn/Ccover/13419419933304609.webp",
		tags: ["游戏"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/盗梦空间/",
		title: "盗梦空间",
		name_cn: "盗梦空间",
		category: "anime",
		status: 2,
		score: 10,
		image: "https://re.tsh520.cn/Acover/盗梦空间.webp",
		tags: ["科幻","悬疑","经典"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/这个杀手不太冷/",
		title: "这个杀手不太冷",
		name_cn: "这个杀手不太冷",
		category: "anime",
		status: 2,
		score: 10,
		image: "https://re.tsh520.cn/Acover/这个杀手不太冷.webp",
		tags: ["剧情","动作","犯罪"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/美丽人生/",
		title: "美丽人生",
		name_cn: "美丽人生",
		category: "anime",
		status: 2,
		score: 10,
		image: "https://re.tsh520.cn/Acover/美丽人生.webp",
		tags: ["剧情","爱情","战争"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/午夜凶铃/",
		title: "午夜凶铃",
		name_cn: "午夜凶铃",
		category: "anime",
		status: 2,
		score: 8,
		image: "https://re.tsh520.cn/Acover/午夜凶铃.webp",
		tags: ["日本","恐怖"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/咒怨/",
		title: "咒怨",
		name_cn: "咒怨",
		category: "anime",
		status: 2,
		score: 6,
		image: "https://re.tsh520.cn/Acover/咒怨.webp",
		tags: ["日本","恐怖"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/咒怨2/",
		title: "咒怨2",
		name_cn: "咒怨2",
		category: "anime",
		status: 2,
		score: 6,
		image: "https://re.tsh520.cn/Acover/咒怨2.webp",
		tags: ["日本","恐怖"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/头号玩家/",
		title: "头号玩家",
		name_cn: "头号玩家",
		category: "anime",
		status: 2,
		score: 8,
		image: "https://re.tsh520.cn/Acover/头号玩家.webp",
		tags: ["科幻","冒险","游戏"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/穿条纹睡衣的男孩/",
		title: "穿条纹睡衣的男孩",
		name_cn: "穿条纹睡衣的男孩",
		category: "anime",
		status: 2,
		score: 8,
		image: "https://re.tsh520.cn/Acover/穿条纹睡衣的男孩.webp",
		tags: ["战争","剧情","感人"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/让子弹飞/",
		title: "让子弹飞",
		name_cn: "让子弹飞",
		category: "anime",
		status: 2,
		score: 8,
		image: "https://re.tsh520.cn/Acover/让子弹飞.webp",
		tags: ["喜剧","动作","西部"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/向阳花/",
		title: "向阳花",
		name_cn: "向阳花",
		category: "anime",
		status: 2,
		score: 8,
		image: "https://re.tsh520.cn/Acover/向阳花.webp",
		tags: ["剧情","犯罪","现代"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/豺狼的日子/",
		title: "豺狼的日子",
		name_cn: "豺狼的日子",
		category: "anime",
		status: 2,
		score: 9,
		image: "https://ph.0824.uk/file/anime/豺狼的日子.jpg",
		tags: ["剧情","动作冒险","悬疑"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/三傻大闹宝莱坞/",
		title: "三傻大闹宝莱坞",
		name_cn: "三傻大闹宝莱坞",
		category: "anime",
		status: 2,
		score: 10,
		image: "https://re.tsh520.cn/Acover/三傻大闹宝莱坞.webp",
		tags: ["喜剧","剧情","爱情"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/九品芝麻官/",
		title: "九品芝麻官",
		name_cn: "九品芝麻官",
		category: "anime",
		status: 2,
		score: 10,
		image: "https://re.tsh520.cn/Acover/九品芝麻官.webp",
		tags: ["喜剧","古装","经典"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/你的名字/",
		title: "你的名字",
		name_cn: "你的名字",
		category: "anime",
		status: 2,
		score: 10,
		image: "https://re.tsh520.cn/Acover/你的名字.webp",
		tags: ["动画","爱情","奇幻"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/功夫/",
		title: "功夫",
		name_cn: "功夫",
		category: "anime",
		status: 2,
		score: 10,
		image: "https://re.tsh520.cn/Acover/功夫.webp",
		tags: ["喜剧","动作","经典"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/千与千寻/",
		title: "千与千寻",
		name_cn: "千与千寻",
		category: "anime",
		status: 2,
		score: 10,
		image: "https://re.tsh520.cn/Acover/千与千寻.webp",
		tags: ["动画","奇幻","剧情"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/唐伯虎点秋香/",
		title: "唐伯虎点秋香",
		name_cn: "唐伯虎点秋香",
		category: "anime",
		status: 2,
		score: 10,
		image: "https://re.tsh520.cn/Acover/唐伯虎点秋香.webp",
		tags: ["喜剧","古装","经典"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/喜剧之王/",
		title: "喜剧之王",
		name_cn: "喜剧之王",
		category: "anime",
		status: 2,
		score: 10,
		image: "https://re.tsh520.cn/Acover/喜剧之王.webp",
		tags: ["喜剧","剧情","经典"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/小丑/",
		title: "小丑",
		name_cn: "小丑",
		category: "anime",
		status: 2,
		score: 8,
		image: "https://re.tsh520.cn/Acover/小丑.webp",
		tags: ["剧情","犯罪","心理"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/少年派的奇幻漂流/",
		title: "少年派的奇幻漂流",
		name_cn: "少年派的奇幻漂流",
		category: "anime",
		status: 2,
		score: 10,
		image: "https://re.tsh520.cn/Acover/少年派的奇幻漂流.webp",
		tags: ["奇幻","冒险","剧情"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/当幸福来敲门/",
		title: "当幸福来敲门",
		name_cn: "当幸福来敲门",
		category: "anime",
		status: 2,
		score: 10,
		image: "https://re.tsh520.cn/Acover/当幸福来敲门.webp",
		tags: ["剧情","传记","家庭"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/我不是药神/",
		title: "我不是药神",
		name_cn: "我不是药神",
		category: "anime",
		status: 2,
		score: 8,
		image: "https://re.tsh520.cn/Acover/我不是药神.webp",
		tags: ["剧情","喜剧","社会"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/摔跤吧爸爸/",
		title: "摔跤吧！爸爸",
		name_cn: "摔跤吧！爸爸",
		category: "anime",
		status: 2,
		score: 8,
		image: "https://re.tsh520.cn/Acover/摔跤吧爸爸.webp",
		tags: ["剧情","传记","运动"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/星际穿越/",
		title: "星际穿越",
		name_cn: "星际穿越",
		category: "anime",
		status: 2,
		score: 10,
		image: "https://re.tsh520.cn/Acover/星际穿越.webp",
		tags: ["科幻","冒险","剧情"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/泰坦尼克号/",
		title: "泰坦尼克号",
		name_cn: "泰坦尼克号",
		category: "anime",
		status: 2,
		score: 10,
		image: "https://re.tsh520.cn/Acover/泰坦尼克号.webp",
		tags: ["爱情","灾难","剧情"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/海边的曼彻斯特/",
		title: "海边的曼彻斯特",
		name_cn: "海边的曼彻斯特",
		category: "anime",
		status: 2,
		score: 8,
		image: "https://re.tsh520.cn/Acover/海边的曼彻斯特.webp",
		tags: ["剧情","家庭","感人"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/白日梦想家/",
		title: "白日梦想家",
		name_cn: "白日梦想家",
		category: "anime",
		status: 2,
		score: 8,
		image: "https://re.tsh520.cn/Acover/白日梦想家.webp",
		tags: ["喜剧","冒险","励志"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/素媛/",
		title: "素媛",
		name_cn: "素媛",
		category: "anime",
		status: 2,
		score: 8,
		image: "https://re.tsh520.cn/Acover/素媛.webp",
		tags: ["剧情","社会","感人"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/绿皮书/",
		title: "绿皮书",
		name_cn: "绿皮书",
		category: "anime",
		status: 2,
		score: 10,
		image: "https://re.tsh520.cn/Acover/绿皮书.webp",
		tags: ["剧情","喜剧","传记"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/肖申克的救赎/",
		title: "肖申克的救赎",
		name_cn: "肖申克的救赎",
		category: "anime",
		status: 2,
		score: 10,
		image: "https://re.tsh520.cn/Acover/肖申克的救赎.webp",
		tags: ["剧情","犯罪","经典"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/蝙蝠侠黑暗骑士/",
		title: "蝙蝠侠：黑暗骑士",
		name_cn: "蝙蝠侠：黑暗骑士",
		category: "anime",
		status: 2,
		score: 8,
		image: "https://re.tsh520.cn/Acover/蝙蝠侠黑暗骑士.webp",
		tags: ["超级英雄","动作","犯罪"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/釜山行/",
		title: "釜山行",
		name_cn: "釜山行",
		category: "anime",
		status: 2,
		score: 8,
		image: "https://re.tsh520.cn/Acover/釜山行.webp",
		tags: ["丧尸","动作","灾难"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/阿甘正传/",
		title: "阿甘正传",
		name_cn: "阿甘正传",
		category: "anime",
		status: 2,
		score: 10,
		image: "https://re.tsh520.cn/Acover/阿甘正传.webp",
		tags: ["剧情","爱情","传记"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
	{
		id: "/bangumi/anime/飞越疯人院/",
		title: "飞越疯人院",
		name_cn: "飞越疯人院",
		category: "anime",
		status: 2,
		score: 8,
		image: "https://re.tsh520.cn/Acover/飞跃疯人院.webp",
		tags: ["剧情","经典"],
		comment: "",
		updated_at: "2026-07-01T14:31:39.808Z",
	},
];
